<font color="#002856"><h1 align="left">Algoritmos de optimización</h1></font>
<font color="#002856"><h2 align="left">VC-2 Diseño de algoritmos</h2></font> 

#### Profesor: Juan Francisco Vallalta Rueda
---

# Medir el tiempo de ejecución

Medir el tiempo de ejecución de un programa es una tarea muy importante, ya que programar no sólo consiste en crear código que funcione, sino código que pueda ser ejecutado en un tiempo razonable.

La librería **time** nos permite medir el tiempo de ejecución en Python, utilizando el método  `time()`.

In [1]:
# Medida del tiempo de ejecucion con time
import time
inicio = time.time()

# Código a medir
time.sleep(10)
# -------------

fin = time.time()
print(fin-inicio) # 1.0005340576171875

10.002641201019287


# Generación de números enteros aleatorios 

In [6]:
# Mödulo random
import random

# Inicialización del rango de números a generar
inicio= 0
fin = 1000
cantidad = 100

# Lista de números aleatorios
numeros_aleatorios = [random.randint(inicio,fin) for i in range(cantidad)]
print(numeros_aleatorios)

[695, 385, 928, 730, 82, 906, 416, 429, 707, 59, 556, 643, 489, 851, 385, 940, 465, 515, 942, 745, 219, 305, 8, 943, 218, 371, 483, 174, 136, 257, 482, 94, 385, 201, 530, 522, 460, 204, 882, 754, 24, 341, 576, 946, 97, 758, 491, 270, 746, 12, 652, 158, 483, 623, 710, 665, 856, 935, 963, 342, 247, 890, 673, 143, 54, 905, 868, 522, 1, 248, 690, 720, 363, 878, 567, 586, 593, 901, 574, 835, 853, 915, 188, 937, 489, 182, 228, 948, 247, 291, 223, 602, 741, 761, 199, 691, 72, 718, 965, 583]


# Ejercicios

## Implementa  una solución para el problema del cambio de moneda en un sistema monetario con las siguientes monedas: {1, 2, 5, 10, 20 , 50}

In [7]:
# Problema de cambio de monedas
# Función que devuelve un diccionario con la cantidad de billetes/monedas de cada tipo
def cambio(importe):
    monedas = { 50:0, 20:0, 10:0, 5:0, 2:0 ,1:0 }
    for k in monedas.keys():
        while (importe >= k):
            monedas[k] += 1
            importe -= k
    return monedas

print(cambio(173))


{50: 3, 20: 1, 10: 0, 5: 0, 2: 1, 1: 1}


# Reto VC-2

## Opción 1: Implementa una solución al problema de las 8 reinas en un tablero 8x8

In [26]:
# Ocho reinas
# Escribe aquí tu código
import numpy as np

n_reinas = 4
tablero = np.zeros((n_reinas,n_reinas))

def checkPos(fila, columna):
    if(np.sum(tablero[:columna]) > 0):
        return False
    for i, j in zip(range(fila, -1, -1),
                    range(columna, -1, -1)):
        if tablero[i][j] == 1:
            return False
    for i, j in zip(range(fila, n_reinas, 1),
                    range(columna, -1, -1)):
        if tablero[i][j] == 1:
            return False
    return True
        
def resolver(columna, n_reinas):
    if(columna >= n_reinas):
        return True
    
    for fila in range(0, n_reinas):
        print(fila, columna)
        if(checkPos(fila, columna)):
            tablero[fila][columna] = 1
            if(resolver(columna + 1, n_reinas)):
                return True
            tablero[fila][columna] = 0

resolver(0, n_reinas)

print(tablero)

0 0
0 1
1 1
2 1
3 1
1 0
0 1
1 1
0 2
1 2
2 2
3 2
2 1
3 1
0 2
1 2
2 2
3 2
2 0
0 1
0 2
1 2
2 2
3 2
1 1
2 1
0 2
1 2
2 2
0 3
1 3
2 3
3 3
3 2
3 1
3 0
0 1
0 2
1 2
2 2
3 2
1 1
0 2
1 2
2 2
3 2
2 1
3 1
0 2
0 3
1 3
2 3
3 3
1 2
2 2
3 2
0 3
1 3
2 3
3 3
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [28]:
tablero[:4]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

## Opción 2: Implementa una solución del problema de las Torres de Hanoi para un número arbitrario n de fichas

In [2]:
# Torres de Hanoy
# Escribe aquí tu código


